CREATE TABLE [ods].[TurnkeySurvey_STH_Survey_2018]
(
[recordid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[started] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modified] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[branched_out] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[over_quota] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[campaign_status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[culture] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[http_referer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[http_user_agent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remote_addr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remote_host] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_page] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_page_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifier] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1_Reg  Season Games Attended] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_Use of Tickets] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_1_Use of Tickets_Other_Specified] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_1_Favorite Benefits_Discounted Pricing] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_2_Favorite Benefits_Access to Every Home Game] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_3_Favorite Benefits_Seat Location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_4_Favorite Benefits_Access to Playoff Strips] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_5_Favorite Benefits_Personal Account Executive] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_6_Favorite Benefits_Dedication Program] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_7_Favorite Benefits_Exclusive STH Events] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_8_Favorite Benefits_Flexible Payment Plans] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_9_Favorite Benefits_Team Store Discount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_10_Favorite Benefits_Other] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_1_Use of Unused Tickets_Give to friends family] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_2_Use of Unused Tickets_Give to clients employees coworkers] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_3_Use of Unused Tickets_Donate to charity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_4_Use of Unused Tickets_Sell tickets through My Ducks Account] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_5_Use of Unused Tickets_Sell tickets via 3rd Party (Stubhub, etc )] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_6_Use of Unused Tickets_Leave tickets unused] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_7_Use of Unused Tickets_N A I always use my tickets] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q5_Overall Satisfaction as a STH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q6_Reason for being unsatisfied] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q7_Likeliness to Renew Tickets] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_1_Not Renewing Because_Team not going in right direction] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_2_Not Renewing Because_The in-game entertainment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_3_Not Renewing Because_Can't enjoy the game due to fan behavior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_4_Not Renewing Because_Overall cost of attending is too high] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_5_Not Renewing Because_Cost of being a STH outweighs the benefits] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_6_Not Renewing Because_I have moved] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_7_Not Renewing Because_Seat Location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_8_Not Renewing Because_Hassle to get to the arena] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_9_Not Renewing Because_Unable to make enough games to make it worthwhile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_10_Not Renewing Because_I can buy games i want on the secondary market] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_11_Not Renewing Because_I cannot resell my tickets due to low perceived demand] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_12_Not Renewing Because_I am unsatisfied with the food and beverage option at Honda Center] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_13_Not Renewing Because_There has been a change with my STH Partner(s)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_Who Do You Direct Questions Towards?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q10_Name of Account Executive] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_1_Rate Your Rep_Responsiveness] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_2_Rate Your Rep_Ability to resolve issues] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_3_Rate Your Rep_Keeps me informed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_4_Rate Your Rep_Overall customer service] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q12_Areas for Rep to improve in] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q13_Interest in learning about referring a friend] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q14_Interest in Premium Seating program] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_1_Sponsor Identified_Honda] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_2_Sponsor Identified_Coca Cola] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_3_Sponsor Identified_Wells Fargo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_4_Sponsor Identified_Pechanga Resort] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_5_Sponsor Identified_Bud Light] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_6_Sponsor Identified_UCLA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_7_Sponsor Identified_Toyota] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_8_Sponsor Identified_7up] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_9_Sponsor Identified_Citizens Business Bank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_10_Sponsor Identified_San Manuel Indian Bingo & Casino] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_11_Sponsor Identified_Coors Light] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_12_Sponsor Identified_USC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_13_Sponsor Identified_Ford] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_14_Sponsor Identified_Pepsi] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_15_Sponsor Identified_Pacific Premier Bank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_16_Sponsor Identified_Pala] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_17_Sponsor Identified_Miller Lite] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_18_Sponsor Identified_UC Irvine] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_19_Sponsor Identified_I don't Know] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_Likeliness to purchase a product affiliated with the Ducks] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_1_Engagement Level_TV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_2_Engagement Level_Radio] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_3_Engagement Level_Facebook] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_4_Engagement Level_Twitter] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_5_Engagement Level_Snapchat] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_6_Engagement Level_Instagram] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
