CREATE TABLE [ods].[SkiData_Rewards]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__SkiData_R__ETL_C__013FDF81] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__SkiData_R__ETL_U__023403BA] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__SkiData_R__ETL_I__032827F3] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RewardID] [int] NULL,
[PortalID] [int] NULL,
[Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostInPoints] [int] NULL,
[NotForSale] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequiredRoleID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdministratorUserID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RewardRedemptionAdministratorMessageTemplateID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RewardRedemptionMessageTemplateID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AvailableStartDate] [datetime] NULL,
[AvailableEndDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QuantityAvailable] [int] NULL,
[QuantityRemaining] [int] NULL,
[DefaultImage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CssClass] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsAuction] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ordinal] [int] NULL,
[IsFeatured] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[DateUpdated] [datetime] NULL,
[UpdatedBy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsShowcased] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RewardCategoryID] [int] NULL,
[RewardURL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BuyNowCost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsVoucher] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RedemptionCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AwardPointActivityID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AwardPointOverride] [int] NULL,
[PerUserCap] [int] NULL,
[LoyaltyProductID] [int] NULL
)
GO
ALTER TABLE [ods].[SkiData_Rewards] ADD CONSTRAINT [PK__SkiData___7EF6BFCDF8D8D725] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
