CREATE TABLE [ods].[Ducks_STH_Survey_2018]
(
[recordid] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[started] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completed] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modified] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[branched_out] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[over_quota] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[campaign_status] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[culture] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[http_referer] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[http_user_agent] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remote_addr] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remote_host] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_page] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_page_number] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifier] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account ID] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1_Reg  Season Games Attended] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_Use of Tickets] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_1_Use of Tickets_Other_Specified] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_1_Favorite Benefits_Discounted Pricing] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_2_Favorite Benefits_Access to Every Home Game] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_3_Favorite Benefits_Seat Location] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_4_Favorite Benefits_Access to Playoff Strips] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_5_Favorite Benefits_Personal Account Executive] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_6_Favorite Benefits_Dedication Program] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_7_Favorite Benefits_Exclusive STH Events] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_8_Favorite Benefits_Flexible Payment Plans] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_9_Favorite Benefits_Team Store Discount] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_10_Favorite Benefits_Other] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_1_Use of Unused Tickets_Give to friends family] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_2_Use of Unused Tickets_Give to clients employees coworkers] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_3_Use of Unused Tickets_Donate to charity] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_4_Use of Unused Tickets_Sell tickets through My Ducks Account] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_5_Use of Unused Tickets_Sell tickets via 3rd Party (Stubhub, etc )] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_6_Use of Unused Tickets_Leave tickets unused] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_7_Use of Unused Tickets_N A I always use my tickets] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q5_Overall Satisfaction as a STH] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q6_Reason for being unsatisfied] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q7_Likeliness to Renew Tickets] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_1_Not Renewing Because_Team not going in right direction] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_2_Not Renewing Because_The in-game entertainment] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_3_Not Renewing Because_Can't enjoy the game due to fan behavior] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_4_Not Renewing Because_Overall cost of attending is too high] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_5_Not Renewing Because_Cost of being a STH outweighs the benefits] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_6_Not Renewing Because_I have moved] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_7_Not Renewing Because_Seat Location] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_8_Not Renewing Because_Hassle to get to the arena] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_9_Not Renewing Because_Unable to make enough games to make it worthwhile] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_10_Not Renewing Because_I can buy games i want on the secondary market] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_11_Not Renewing Because_I cannot resell my tickets due to low perceived demand] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_12_Not Renewing Because_I am unsatisfied with the food and beverage option at Honda Center] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_13_Not Renewing Because_There has been a change with my STH Partner(s)] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_Who Do You Direct Questions Towards?] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q10_Name of Account Executive] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_1_Rate Your Rep_Responsiveness] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_2_Rate Your Rep_Ability to resolve issues] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_3_Rate Your Rep_Keeps me informed] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_4_Rate Your Rep_Overall customer service] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q12_Areas for Rep to improve in] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q13_Interest in learning about referring a friend] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q14_Interest in Premium Seating program] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_1_Sponsor Identified_Honda] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_2_Sponsor Identified_Coca Cola] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_3_Sponsor Identified_Wells Fargo] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_4_Sponsor Identified_Pechanga Resort] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_5_Sponsor Identified_Bud Light] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_6_Sponsor Identified_UCLA] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_7_Sponsor Identified_Toyota] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_8_Sponsor Identified_7up] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_9_Sponsor Identified_Citizens Business Bank] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_10_Sponsor Identified_San Manuel Indian Bingo & Casino] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_11_Sponsor Identified_Coors Light] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_12_Sponsor Identified_USC] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_13_Sponsor Identified_Ford] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_14_Sponsor Identified_Pepsi] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_15_Sponsor Identified_Pacific Premier Bank] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_16_Sponsor Identified_Pala] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_17_Sponsor Identified_Miller Lite] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_18_Sponsor Identified_UC Irvine] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_19_Sponsor Identified_I don't Know] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_Likeliness to purchase a product affiliated with the Ducks] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_1_Engagement Level_TV] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_2_Engagement Level_Radio] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_3_Engagement Level_Facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_4_Engagement Level_Twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_5_Engagement Level_Snapchat] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_6_Engagement Level_Instagram] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
