CREATE TABLE [ods].[Turnkey_STH_Survey]
(
[ETL__ID] [bigint] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[recordid] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[started] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completed] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modified] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[branched_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[over_quota] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[campaign_status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[culture] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[http_referer] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[http_user_agent] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remote_addr] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remote_host] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_page] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_page_number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifier] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_ID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1_Reg._Season_Games_Attended_(1=0-5,_2=5-10,_3=10-15,_4=15-20)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_Use_of_Tickets_(1=Personal,_2=Business)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_1_Use_of_Tickets_Other_Specified] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_1_Favorite_Benefits_Discounted_Pricing_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_2_Favorite_Benefits_Access_to_Every_Home_Game_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_3_Favorite_Benefits_Seat_Location_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_4_Favorite_Benefits_Access_to_Playoff_Strips_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_5_Favorite_Benefits_Personal_Account_Executive_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_6_Favorite_Benefits_Dedication_Program_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_7_Favorite_Benefits_Exclusive_STH_Events_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_8_Favorite_Benefits_Flexible_Payment_Plans_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_9_Favorite_Benefits_Team_Store_Discount_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3_10_Favorite_Benefits_Other_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_1_Use_of_Unused_Tickets_Give_to_friends/family_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_2_Use_of_Unused_Tickets_Give_to_clients/employees/coworkers_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_3_Use_of_Unused_Tickets_Donate_to_charity_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_4_Use_of_Unused_Tickets_Sell_tickets_through_My_Ducks_Account_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_5_Use_of_Unused_Tickets_Sell_tickets_via_3rd_Party_(Stubhub,_etc.)_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_6_Use_of_Unused_Tickets_Leave_tickets_unused_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4_7_Use_of_Unused_Tickets_N/A_I_always_use_my_tickets_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q5_Overall_Satisfaction_as_a_STH_(1=Very_Sat.,_4=Very_Unsat.)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q6_Reason_for_being_unsatisfied] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q7_Likeliness_to_Renew_Tickets_(1=Def._Likely,_4=Def._Not_Likely)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_1_Not_Renewing_Because_Team_not_going_in_right_direction_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_2_Not_Renewing_Because_The_in-game_entertainment_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_3_Not_Renewing_Because_Can't_enjoy_the_game_due_to_fan_behavior_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_4_Not_Renewing_Because_Overall_cost_of_attending_is_too_high_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_5_Not_Renewing_Because_Cost_of_being_a_STH_outweighs_the_benefits_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_6_Not_Renewing_Because_I_have_moved_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_7_Not_Renewing_Because_Seat_Location_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_8_Not_Renewing_Because_Hassle_to_get_to_the_arena_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_9_Not_Renewing_Because_Unable_to_make_enough_games_to_make_it_worthwhile_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_10_Not_Renewing_Because_I_can_buy_games_i_want_on_the_secondary_market_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_11_Not_Renewing_Because_I_cannot_resell_my_tickets_due_to_low_perceived_demand_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_12_Not_Renewing_Because_I_am_unsatisfied_with_the_food_and_beverage_option_at_Honda_Center_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8_13_Not_Renewing_Because_There_has_been_a_change_with_my_STH_Partner(s)_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_Who_Do_You_Direct_Questions_Towards?_(1=Account_Rep,_2=_Ticket_Office,_3=IDK)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q10_Name_of_Account_Executive_(1=DA,_2=KM,_3=MM,_4=CN,_5=NM,_6=IDK)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_1_Rate_Your_Rep_Responsiveness_(1=Very_Sat.,_4=Very_Unsat.,_5=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_2_Rate_Your_Rep_Ability_to_resolve_issues_(1=Very_Sat.,_4=Very_Unsat.,_5=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_3_Rate_Your_Rep_Keeps_me_informed_(1=Very_Sat.,_4=Very_Unsat.,_5=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_4_Rate_Your_Rep_Overall_customer_service_(1=Very_Sat.,_4=Very_Unsat.,_5=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q12_Areas_for_Rep_to_improve_in] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q13_Interest_in_learning_about_referring_a_friend_(1=yes,_2=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q14_Interest_in_Premium_Seating_program_(1=yes,_2=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_1_Sponsor_Identified_Honda_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_2_Sponsor_Identified_Coca_Cola_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_3_Sponsor_Identified_Wells_Fargo_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_4_Sponsor_Identified_Pechanga_Resort_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_5_Sponsor_Identified_Bud_Light_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_6_Sponsor_Identified_UCLA_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_7_Sponsor_Identified_Toyota_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_8_Sponsor_Identified_7up_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_9_Sponsor_Identified_Citizens_Business_Bank_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_10_Sponsor_Identified_San_Manuel_Indian_Bingo_&_Casino_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_11_Sponsor_Identified_Coors_Light_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_12_Sponsor_Identified_USC_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_13_Sponsor_Identified_Ford_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_14_Sponsor_Identified_Pepsi_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_15_Sponsor_Identified_Pacific_Premier_Bank_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_16_Sponsor_Identified_Pala_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_17_Sponsor_Identified_Miller_Lite_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_18_Sponsor_Identified_UC_Irvine_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15_19_Sponsor_Identified_I_don't_Know_(1=yes,_0=no)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_Likeliness_to_purchase_a_product_affiliated_with_the_Ducks_(1=Strongly_Agree,_4=_Strongly_Disagree,_5=Neither)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_1_Engagement_Level_TV_(1=Very_Engaged,_3=Not,_4=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_2_Engagement_Level_Radio_(1=Very_Engaged,_3=Not,_4=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_3_Engagement_Level_Facebook_(1=Very_Engaged,_3=Not,_4=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_4_Engagement_Level_Twitter_(1=Very_Engaged,_3=Not,_4=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_5_Engagement_Level_Snapchat_(1=Very_Engaged,_3=Not,_4=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17_6_Engagement_Level_Instagram_(1=Very_Engaged,_3=Not,_4=N/A)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ods].[Turnkey_STH_Survey] ADD CONSTRAINT [PK__Turnkey___C4EA24451B6A9083] PRIMARY KEY CLUSTERED  ([ETL__ID])
GO
